DEFAULT_ALLOWED_PARAMETERS_ON_LOGGING = 
  [
    'api_key',
    'app_name',
    'browser_time',
    'callback', 
    'cookie_enabled',
    'description',
    'file',
    'href',
    'language',
    'level',
    'line',
    'message',
    'parameters',
    'parent_url', 
    'platform',
    'product',
    'protocol',
    'stack_trace',
    'window_event',
    'user_agent',
    'user_address'
  ]
